HOW_BUILT = "The sequence follows the statutory Year 2 spelling rules from the National Curriculum (English Appendix 1), ordered so each week's rule builds logically on the one before — sounds first, then suffixes, then apostrophes/homophones, then the Year 2 common exception words. Because your class is strong, the pace is faster than a typical Year 2 scheme: new rules are introduced roughly weekly rather than fortnightly, and each list includes 1–2 challenge words that stretch beyond the minimum (marked with *) — words that follow the rule but are longer or less frequent, so quick finishers still have something to work for."

TEST_FORMAT = "Weekly test format suggestion: 10 spellings + 2 dictation sentences using two of the words in context (tests application, not just recall — bright spellers often pattern-match a word list without being able to use the words correctly)."

PACING = "Pacing: 36 weeks fits a school year with room for INSET days, assessment weeks, and a settling-in week at the very start. If your year has more teaching weeks, repeat weeks 35–36 as a rolling review, or fold in extra homophones."

DIFFERENTIATION_NOTES = [
    "Challenge words (*) aren't compulsory — use them as the \"if you finish early\" extension or as the dictation-sentence word, so accuracy under context is tested, not just rote recall.",
    "Consider a \"spot the rule\" starter each Monday: show the 10 words and ask the children to work out the shared pattern themselves before you name it — this suits children who are ready to reason about spelling rather than just memorise.",
    "For weeks with exception words (28–34), pair each test with one \"apply the rule\" bonus word that isn't on any list, to check they're generalising rather than memorising a fixed set.",
    "Revisit trickier rules (doubling, drop-e, y→i) briefly in weeks 35–36 dictation sentences, since these are the ones bright children still misapply under time pressure even when they know the rule.",
]

# Sentences and meanings for every word — UK English throughout.
# Sentence: simple, 8–14 words, age-appropriate for Year 2 (6–7 year olds).
# Meaning: child-friendly definition, under 12 words.
WORD_DATA = {
    # Week 1 — consonant blends
    "frost": {"sentence": "Frost covered the leaves with a sparkly white coat.", "meaning": "A thin layer of ice that forms when it is very cold."},
    "stamp": {"sentence": "She put a stamp on the letter before posting it.", "meaning": "To press your foot down hard, or a sticky label for post."},
    "splash": {"sentence": "He jumped in the puddle and made a big splash.", "meaning": "To hit water so that it sprays out noisily."},
    "string": {"sentence": "We tied the parcel up with a piece of string.", "meaning": "A thin piece of twisted threads used for tying things."},
    "scrunch": {"sentence": "She liked to scrunch the dry autumn leaves underfoot.", "meaning": "To crush or squeeze something so it makes a crunching sound."},
    "drift": {"sentence": "Snowflakes began to drift slowly down from the grey sky.", "meaning": "To float or move gently without being steered."},
    "thrust": {"sentence": "He thrust the door open and ran outside to play.", "meaning": "To push something suddenly and with force."},
    "sprint": {"sentence": "She did a sprint to the finish line and won!", "meaning": "To run as fast as you possibly can."},
    "crisp": {"sentence": "The air felt crisp and cold on a winter morning.", "meaning": "Pleasantly firm and fresh, or a thin fried potato snack."},
    "blast": {"sentence": "A blast of cold wind blew his hat right off.", "meaning": "A strong rush of air or a sudden loud noise."},
    # Week 2 — /dʒ/ dge/ge
    "badge": {"sentence": "She wore a shiny gold badge on her school jumper.", "meaning": "A small label or pin that shows who you are."},
    "bridge": {"sentence": "We walked across the bridge over the fast-flowing river.", "meaning": "A structure built so people can cross over water or a road."},
    "fudge": {"sentence": "Granny made a delicious batch of chocolate fudge as a treat.", "meaning": "A soft, sweet made from sugar, butter, and milk."},
    "hedge": {"sentence": "Birds were nesting in the tall green hedge by the garden.", "meaning": "A row of bushes planted close together to form a boundary."},
    "lodge": {"sentence": "They stayed in a cosy wooden lodge in the snowy mountains.", "meaning": "A small house, often in the countryside or mountains."},
    "cage": {"sentence": "The hamster slept in a cosy corner of its cage.", "meaning": "A container with bars used to keep animals safely inside."},
    "huge": {"sentence": "That elephant was huge — bigger than a double-decker bus!", "meaning": "Extremely large in size."},
    "stage": {"sentence": "All the children walked onto the stage for the school play.", "meaning": "A raised platform where people perform in front of an audience."},
    "page": {"sentence": "Turn the page carefully so you do not tear it.", "meaning": "One side of a sheet of paper in a book."},
    "edge": {"sentence": "She balanced carefully on the edge of the swimming pool.", "meaning": "The thin line where something ends or begins."},
    # Week 3 — /dʒ/ spelled g
    "gem": {"sentence": "She found a beautiful red gem glittering in the sand.", "meaning": "A precious stone, such as a ruby or emerald."},
    "giant": {"sentence": "A giant oak tree stood in the middle of the field.", "meaning": "Something or someone much bigger than normal."},
    "magic": {"sentence": "He waved his wand and said the magic words.", "meaning": "A mysterious power that makes impossible things seem to happen."},
    "energy": {"sentence": "Running around the playground uses lots of energy.", "meaning": "The power you need to do things or keep moving."},
    "ginger": {"sentence": "Mum added fresh ginger to the soup to make it spicy.", "meaning": "A root with a warm, spicy flavour used in cooking."},
    "gym": {"sentence": "We played indoor games in the gym on a rainy day.", "meaning": "A large room with equipment for exercise and sport."},
    "danger": {"sentence": "The sign warned drivers that there was danger on the road.", "meaning": "Something that could hurt you or cause harm."},
    "engine": {"sentence": "The engine roared loudly as the train left the station.", "meaning": "A machine that uses power to make something move."},
    "gentle": {"sentence": "Be gentle when you stroke the baby rabbit.", "meaning": "Soft and careful, not rough or harsh."},
    "giraffe": {"sentence": "A giraffe stretched its long neck to reach the highest leaves.", "meaning": "A very tall African animal with a long neck and spotted coat."},
    # Week 4 — /s/ spelled c
    "ice": {"sentence": "Be careful — there is ice on the path this morning.", "meaning": "Frozen water that is hard and slippery."},
    "dance": {"sentence": "She loves to dance to her favourite songs in the kitchen.", "meaning": "To move your body in time to music."},
    "fence": {"sentence": "The dog jumped over the wooden fence into next door's garden.", "meaning": "A barrier made of wood or wire around a space."},
    "city": {"sentence": "London is a very busy and exciting city to visit.", "meaning": "A large, important town where many people live and work."},
    "circle": {"sentence": "Draw a circle around the correct answer on your worksheet.", "meaning": "A perfectly round flat shape with no corners."},
    "pencil": {"sentence": "She sharpened her pencil before starting the maths test.", "meaning": "A thin stick of graphite inside wood, used for writing."},
    "cycle": {"sentence": "Dad goes for a cycle along the canal path every weekend.", "meaning": "To ride a bicycle, or a series of events that repeat."},
    "cell": {"sentence": "Every living thing is made up of tiny cells.", "meaning": "The smallest basic unit of a living thing."},
    "race": {"sentence": "Who won the egg-and-spoon race on sports day?", "meaning": "A competition to see who is the fastest."},
    "mice": {"sentence": "The mice ate all the crumbs that fell under the table.", "meaning": "More than one mouse — small furry animals with long tails."},
    # Week 5 — kn/gn
    "knee": {"sentence": "She scraped her knee when she fell off her scooter.", "meaning": "The joint in the middle of your leg that lets it bend."},
    "knock": {"sentence": "Please knock on the door before you come into the room.", "meaning": "To hit a surface sharply to make a noise."},
    "knife": {"sentence": "Use a knife and fork to eat your dinner properly.", "meaning": "A tool with a sharp blade used for cutting food."},
    "know": {"sentence": "Do you know the answer to question number five?", "meaning": "To have information about something in your mind."},
    "knot": {"sentence": "Tie a knot in the end of the thread before sewing.", "meaning": "A fastening made by looping and tightening string or rope."},
    "gnaw": {"sentence": "The puppy began to gnaw on its favourite chew toy.", "meaning": "To bite and chew something hard over and over again."},
    "gnome": {"sentence": "Gran has a little red gnome sitting in her garden.", "meaning": "A small imaginary creature in fairy tales, often living underground."},
    "sign": {"sentence": "The sign on the door said the library was closed.", "meaning": "A board or notice that gives information or a warning."},
    "gnat": {"sentence": "A tiny gnat flew straight into his ear at the picnic.", "meaning": "A very small flying insect that bites."},
    "kneel": {"sentence": "Kneel down on the mat to stretch your legs properly.", "meaning": "To go down onto one or both knees."},
    # Week 6 — wr
    "write": {"sentence": "Write your name neatly at the top of the page.", "meaning": "To make letters or words with a pen or pencil."},
    "wrist": {"sentence": "She wore a sparkly bracelet around her wrist.", "meaning": "The thin part of your arm just above your hand."},
    "wrap": {"sentence": "Help me wrap the birthday present in pretty paper.", "meaning": "To cover something completely by folding paper or cloth around it."},
    "wrong": {"sentence": "He gave the wrong answer, so he tried again.", "meaning": "Not correct; not the right one."},
    "wreck": {"sentence": "Divers discovered an old ship wreck on the ocean floor.", "meaning": "Something that has been badly damaged or destroyed."},
    "wrinkle": {"sentence": "She spotted a wrinkle in her freshly ironed school skirt.", "meaning": "A small crease or line in fabric or skin."},
    "wren": {"sentence": "A tiny wren hopped along the wall in our garden.", "meaning": "A very small brown bird with a short upright tail."},
    "wrestle": {"sentence": "The two brothers would often wrestle playfully on the lawn.", "meaning": "To grapple and struggle with someone using your body."},
    "wreath": {"sentence": "Mum hung a holly wreath on the front door at Christmas.", "meaning": "A circular decoration made from leaves, flowers, or branches."},
    "wriggle": {"sentence": "Stop trying to wriggle out of tidying your bedroom!", "meaning": "To twist and turn your body in small movements."},
    # Week 7 — unstressed /l/
    "table": {"sentence": "Put your books on the table before we start the lesson.", "meaning": "A piece of furniture with a flat top and legs."},
    "apple": {"sentence": "She crunched into a juicy red apple at break time.", "meaning": "A round fruit that can be red, green, or yellow."},
    "little": {"sentence": "Only a little bit of milk is left in the jug.", "meaning": "Small in size or amount."},
    "camel": {"sentence": "A camel can travel for days across the desert without water.", "meaning": "A large animal with one or two humps on its back."},
    "tunnel": {"sentence": "The train disappeared into the dark tunnel under the hill.", "meaning": "A long passage dug through the ground or a hill."},
    "travel": {"sentence": "We travel to France every summer on the ferry.", "meaning": "To go from one place to another, often far away."},
    "metal": {"sentence": "The railings outside the school were made of shiny metal.", "meaning": "A hard material like iron, steel, or gold."},
    "pedal": {"sentence": "Push down on the pedal to make the bicycle move faster.", "meaning": "A lever you press with your foot to power a machine."},
    "hospital": {"sentence": "The doctor at the hospital helped me when I broke my arm.", "meaning": "A place where ill or injured people go to get better."},
    "animal": {"sentence": "A dog is a popular animal to keep as a pet.", "meaning": "A living creature that is not a plant or a person."},
    # Week 8 — words ending -y
    "happy": {"sentence": "She felt happy when she saw her best friend at school.", "meaning": "Feeling pleased and full of joy."},
    "funny": {"sentence": "His funny joke made the whole class burst out laughing.", "meaning": "Something that makes you laugh or smile."},
    "family": {"sentence": "Our family always eats dinner together at the kitchen table.", "meaning": "A group of people related to each other, like parents and children."},
    "party": {"sentence": "She blew out all her candles at her birthday party.", "meaning": "A celebration where people come together to have fun."},
    "twenty": {"sentence": "There are twenty children sitting on the carpet in the hall.", "meaning": "The number that is two tens, written as 20."},
    "story": {"sentence": "Please read us one more story before we go to sleep.", "meaning": "A description of events, real or made up, told or written down."},
    "sunny": {"sentence": "It was a sunny day, so we ate lunch outside.", "meaning": "Bright with sunshine; lots of light from the sun."},
    "lucky": {"sentence": "He felt lucky to find a pound coin on the pavement.", "meaning": "Having good things happen to you by chance."},
    "hungry": {"sentence": "After swimming for an hour, she was very hungry.", "meaning": "Feeling like you need food because your tummy is empty."},
    "memory": {"sentence": "Gran has a wonderful memory for names and faces.", "meaning": "The ability to remember things from the past."},
    # Week 9 — plural -es on nouns ending -y
    "babies": {"sentence": "Three babies were asleep in their prams in the park.", "meaning": "More than one baby — very young children."},
    "ladies": {"sentence": "Two ladies sat knitting on a bench in the sunshine.", "meaning": "More than one woman or girl, used as a polite term."},
    "cities": {"sentence": "Many cities in the UK have big museums and art galleries.", "meaning": "More than one city — large, important towns."},
    "families": {"sentence": "Both families met at the park for a big picnic.", "meaning": "More than one family — groups of people related to each other."},
    "ponies": {"sentence": "Six ponies trotted around the paddock in a line.", "meaning": "More than one pony — small horses."},
    "stories": {"sentence": "The children read lots of different stories during Book Week.", "meaning": "More than one story — accounts of events, real or imagined."},
    "parties": {"sentence": "She went to three birthday parties in one weekend.", "meaning": "More than one party — celebrations with friends."},
    "countries": {"sentence": "Some children in our class have lived in different countries.", "meaning": "More than one country — large areas of land with their own governments."},
    "hobbies": {"sentence": "His hobbies include football, reading, and drawing dinosaurs.", "meaning": "More than one hobby — activities you enjoy in your free time."},
    "bunnies": {"sentence": "Two fluffy white bunnies hopped around the hutch.", "meaning": "More than one bunny — a friendly word for rabbits."},
    # Week 10 — suffixes on -y words (y→i)
    "tried": {"sentence": "She tried her hardest at the spelling test today.", "meaning": "Made an effort to do something in the past."},
    "tries": {"sentence": "He tries his best at every piece of work he does.", "meaning": "Makes an effort to do something (happening now or usually)."},
    "trying": {"sentence": "She is trying to learn her times tables this week.", "meaning": "Making an effort to do something right now."},
    "happier": {"sentence": "She felt happier once she had spoken to her teacher.", "meaning": "More happy than before."},
    "happiest": {"sentence": "That was the happiest day of the whole summer holiday.", "meaning": "The most happy — more happy than anyone or anything else."},
    "carried": {"sentence": "He carried the heavy shopping bags from the car.", "meaning": "Held and moved something from one place to another (past)."},
    "carrying": {"sentence": "She is carrying all her PE kit in a big bag.", "meaning": "Holding and moving something right now."},
    "dried": {"sentence": "She dried her hair with a towel after swimming.", "meaning": "Removed water from something (past tense)."},
    "hurried": {"sentence": "They hurried down the road so they would not be late.", "meaning": "Moved or did something faster than normal (past tense)."},
    "replying": {"sentence": "She is replying to her pen pal's letter right now.", "meaning": "Writing or saying something in response to a message."},
    # Week 11 — drop-e suffixes
    "hoping": {"sentence": "She is hoping it will be sunny for the school fete.", "meaning": "Wanting something good to happen."},
    "hoped": {"sentence": "He hoped the dentist would not take too long.", "meaning": "Wanted something good to happen (past tense)."},
    "shining": {"sentence": "The sun was shining brightly through the classroom windows.", "meaning": "Giving out or reflecting a bright light."},
    "riding": {"sentence": "He loves riding his bike along the towpath by the canal.", "meaning": "Sitting on and travelling with something like a horse or bike."},
    "rider": {"sentence": "The rider wore a hard hat to keep her head safe.", "meaning": "A person who rides a horse, bike, or other vehicle."},
    "baking": {"sentence": "Mum is baking a chocolate cake for the school fair.", "meaning": "Cooking food in the oven using dry heat."},
    "baker": {"sentence": "The baker got up at four in the morning to make fresh bread.", "meaning": "Someone who bakes and sells bread and cakes."},
    "smiling": {"sentence": "She was smiling when she got full marks on her test.", "meaning": "Making a happy expression by curving your mouth upwards."},
    "smiled": {"sentence": "He smiled when his teacher said his writing was brilliant.", "meaning": "Made a happy expression (past tense)."},
    "deciding": {"sentence": "She is deciding which book to read next from the shelf.", "meaning": "Thinking carefully and then choosing between options."},
    # Week 12 — doubling consonant
    "hopping": {"sentence": "A frog was hopping across the lily pads on the pond.", "meaning": "Jumping on one or both legs in small, quick jumps."},
    "hopped": {"sentence": "The little rabbit hopped away into the long grass.", "meaning": "Jumped on one or both legs (past tense)."},
    "running": {"sentence": "She was running so fast that she won the race easily.", "meaning": "Moving quickly by taking rapid steps."},
    "runner": {"sentence": "Every runner was given a medal at the end of the race.", "meaning": "A person who runs in a race or for exercise."},
    "biggest": {"sentence": "That is the biggest strawberry I have ever seen in my life!", "meaning": "The most large — larger than everything else."},
    "sadder": {"sentence": "He felt sadder when his best friend moved to a new school.", "meaning": "More sad than before."},
    "patted": {"sentence": "She gently patted the dog on its soft furry head.", "meaning": "Touched something lightly and repeatedly with a flat hand."},
    "humming": {"sentence": "She was humming her favourite song while she painted.", "meaning": "Making a continuous musical sound with your mouth closed."},
    "swimmer": {"sentence": "She is a fantastic swimmer who wins medals at galas.", "meaning": "A person who swims, especially in races."},
    "forgetting": {"sentence": "He keeps forgetting to bring his reading book to school.", "meaning": "Not being able to remember something."},
    # Week 13 — /ɒ/ after w/qu
    "wander": {"sentence": "We love to wander through the woods on a Sunday afternoon.", "meaning": "To walk slowly without a fixed destination."},
    "swan": {"sentence": "A beautiful white swan glided silently across the lake.", "meaning": "A large white bird with a long neck that lives near water."},
    "quantity": {"sentence": "Can you measure the correct quantity of flour for the recipe?", "meaning": "An amount or number of something."},
    "squash": {"sentence": "Would you like a glass of orange squash after football?", "meaning": "A sweet drink made from fruit juice, or to press something flat."},
    "wasp": {"sentence": "A wasp landed on her sandwich at the summer picnic.", "meaning": "A yellow-and-black flying insect that can sting."},
    "quality": {"sentence": "She always does quality work because she takes her time.", "meaning": "How good something is."},
    "quarrel": {"sentence": "They had a quarrel over whose turn it was to choose the game.", "meaning": "An angry argument or disagreement."},
    "wallet": {"sentence": "Dad keeps his cards and money safe inside his brown wallet.", "meaning": "A small flat case for carrying money and cards."},
    "swap": {"sentence": "Can I swap my orange for your apple?", "meaning": "To exchange one thing for another."},
    "squabble": {"sentence": "Stop the squabble — there is plenty of cake for everyone.", "meaning": "A noisy argument about something unimportant."},
    # Week 14 — /ɜː/ spelled or after w
    "word": {"sentence": "She learnt a new word in French today at school.", "meaning": "A unit of language with a meaning."},
    "work": {"sentence": "Hard work and practice help you get better at spelling.", "meaning": "An activity that needs effort, often done as a job."},
    "world": {"sentence": "One day she would love to travel all around the world.", "meaning": "The planet Earth and all the people and places on it."},
    "worm": {"sentence": "A pink worm wriggled out of the soil in the garden.", "meaning": "A small creature with a long soft body and no legs."},
    "worth": {"sentence": "All your hard work is really worth it in the end.", "meaning": "Having a value equal to something."},
    "worship": {"sentence": "People of many faiths worship in their own special way.", "meaning": "To show great love and respect for a god."},
    "worse": {"sentence": "His cold got worse when he went out in the rain.", "meaning": "More bad or unpleasant than before."},
    "worst": {"sentence": "That was the worst storm the village had seen in years.", "meaning": "The most bad — worse than everything else."},
    "network": {"sentence": "Our school is part of a network of local primary schools.", "meaning": "A connected group of things or people."},
    "wordless": {"sentence": "She was wordless with surprise when she saw the huge gift.", "meaning": "Unable to speak, usually because of surprise or emotion."},
    # Week 15 — /ɔː/ spelled ar after w
    "warm": {"sentence": "Curl up with a warm blanket and a good book.", "meaning": "Having a comfortable level of heat; not cold."},
    "ward": {"sentence": "The children's ward at the hospital was painted bright yellow.", "meaning": "A room in a hospital where patients are looked after."},
    "warn": {"sentence": "Please warn me if you see a wasp anywhere near me!", "meaning": "To tell someone about a possible danger before it happens."},
    "wart": {"sentence": "The witch in the story had a wart on the end of her nose.", "meaning": "A small, hard lump that can grow on the skin."},
    "dwarf": {"sentence": "In the fairy tale, Snow White lived with seven dwarfs.", "meaning": "A mythical creature much smaller than a human, or a very small version of something."},
    "award": {"sentence": "She won an award for her brilliant science project.", "meaning": "A prize given to someone for doing something very well."},
    "reward": {"sentence": "His reward for tidying his room was extra screen time.", "meaning": "Something nice given to someone for good behaviour or effort."},
    "swarm": {"sentence": "A swarm of bees flew out of the hive into the garden.", "meaning": "A large group of insects moving together."},
    "towards": {"sentence": "She walked quickly towards the school gate at home time.", "meaning": "In the direction of something."},
    "warden": {"sentence": "The park warden made sure everyone followed the rules.", "meaning": "A person in charge of looking after a place or enforcing rules."},
    # Week 16 — /ʒ/ spelled s
    "treasure": {"sentence": "They dug up an old box and found treasure inside.", "meaning": "Very valuable things, like gold, jewels, or something precious to you."},
    "measure": {"sentence": "Use a ruler to measure the length of your pencil.", "meaning": "To find out the size or amount of something."},
    "pleasure": {"sentence": "It was a pleasure to meet your wonderful family today.", "meaning": "A feeling of enjoyment or happiness."},
    "usual": {"sentence": "She sat in her usual seat at the front of the class.", "meaning": "Normal; the same as always."},
    "television": {"sentence": "We watched a programme about ocean creatures on television.", "meaning": "An electronic device that shows moving pictures and sound."},
    "casual": {"sentence": "Friday is casual clothes day at our school.", "meaning": "Relaxed and informal; not special or formal."},
    "visual": {"sentence": "She used a visual display to help explain her ideas.", "meaning": "Something seen with the eyes; relating to sight."},
    "leisure": {"sentence": "Reading is her favourite leisure activity at the weekend.", "meaning": "Free time when you can relax and do things you enjoy."},
    "azure": {"sentence": "On holiday, the sky above the sea was a perfect azure blue.", "meaning": "A bright, clear blue colour, like a sunny sky."},
    "unusual": {"sentence": "It is unusual to see snow in September in England.", "meaning": "Not normal; different from what usually happens."},
    # Week 17 — suffix -ment
    "enjoyment": {"sentence": "She got lots of enjoyment from painting pictures in her sketchbook.", "meaning": "The feeling of pleasure from doing something you like."},
    "argument": {"sentence": "They settled their argument by talking calmly to each other.", "meaning": "A disagreement between people, often spoken loudly."},
    "government": {"sentence": "The government makes the laws that everyone in the country follows.", "meaning": "The group of people who run and make decisions for a country."},
    "movement": {"sentence": "There was a sudden movement in the long grass near the pond.", "meaning": "The act of moving or changing position."},
    "statement": {"sentence": "The teacher asked him to make a clear statement about what he saw.", "meaning": "A sentence that gives information about something."},
    "equipment": {"sentence": "Always put the PE equipment away tidily after the lesson.", "meaning": "The tools or items needed for a particular activity."},
    "payment": {"sentence": "Mum made a payment for the school trip online.", "meaning": "Money given in exchange for something."},
    "treatment": {"sentence": "The vet gave the injured bird careful treatment.", "meaning": "Care given to someone who is ill or hurt."},
    "excitement": {"sentence": "There was great excitement on the morning of the school trip.", "meaning": "A strong feeling of happiness and eagerness."},
    "arrangement": {"sentence": "Mum made an arrangement to collect us from school at four.", "meaning": "A plan or preparation made in advance."},
    # Week 18 — suffix -ness
    "happiness": {"sentence": "Playing with her puppy fills her with pure happiness.", "meaning": "A feeling of great joy and contentment."},
    "kindness": {"sentence": "Showing kindness to others makes the world a nicer place.", "meaning": "The quality of being friendly, generous, and caring."},
    "sadness": {"sentence": "She felt a deep sadness when her goldfish died.", "meaning": "A feeling of unhappiness or sorrow."},
    "darkness": {"sentence": "She switched on her torch when it became total darkness.", "meaning": "The absence of light; when it is very dark."},
    "illness": {"sentence": "He missed three days of school because of his illness.", "meaning": "A sickness or disease that makes you feel unwell."},
    "weakness": {"sentence": "His one weakness in maths was remembering his times tables.", "meaning": "A point where someone or something is not as strong."},
    "thickness": {"sentence": "Check the thickness of the card before you cut it.", "meaning": "How thick or wide something is from one side to the other."},
    "business": {"sentence": "Gran runs a small business selling homemade jams and chutneys.", "meaning": "Work that involves buying and selling things or providing a service."},
    "awareness": {"sentence": "Road safety awareness is very important for young children.", "meaning": "Knowing about and understanding something."},
    "fairness": {"sentence": "The teacher was known for her fairness towards all the children.", "meaning": "Treating everyone equally and in the right way."},
    # Week 19 — suffix -ful
    "careful": {"sentence": "Be careful when you carry those mugs — they are heavy.", "meaning": "Doing things with attention to avoid mistakes or accidents."},
    "helpful": {"sentence": "It is really helpful when you tidy up without being asked.", "meaning": "Making things easier for someone else; being useful."},
    "useful": {"sentence": "A dictionary is a very useful book to have on your shelf.", "meaning": "Able to help or be used for something."},
    "playful": {"sentence": "The playful kitten kept swatting the ball of wool.", "meaning": "Full of fun and wanting to play."},
    "wonderful": {"sentence": "Thank you for a truly wonderful performance this afternoon.", "meaning": "Extremely good or impressive; causing wonder."},
    "colourful": {"sentence": "She wore a colourful outfit to the fancy dress party.", "meaning": "Full of bright, varied colours."},
    "thankful": {"sentence": "He was thankful that his friend had saved him a seat.", "meaning": "Feeling or showing gratitude for something."},
    "painful": {"sentence": "The injection was a bit painful, but it was over quickly.", "meaning": "Causing physical or emotional pain."},
    "powerful": {"sentence": "The powerful wind blew the umbrellas inside out.", "meaning": "Having great strength or force."},
    "beautiful": {"sentence": "The sunset over the sea was the most beautiful thing she had ever seen.", "meaning": "Very pleasing to look at or hear."},
    # Week 20 — suffix -less
    "careless": {"sentence": "A careless mistake cost her a mark on the spelling test.", "meaning": "Not taking enough care; making avoidable mistakes."},
    "helpless": {"sentence": "The tiny kitten looked helpless until we picked it up.", "meaning": "Unable to look after yourself or do things without help."},
    "useless": {"sentence": "A broken pencil is useless without a sharpener nearby.", "meaning": "Having no practical use; not working properly."},
    "harmless": {"sentence": "The spider in the bath is harmless — it will not bite.", "meaning": "Not able to cause any harm or damage."},
    "endless": {"sentence": "It seemed like the walk through the forest was endless.", "meaning": "Having no end; continuing for a very long time."},
    "homeless": {"sentence": "The charity helps homeless people find safe places to stay.", "meaning": "Having no home to live in."},
    "painless": {"sentence": "The nurse promised the injection would be completely painless.", "meaning": "Causing no pain at all."},
    "fearless": {"sentence": "The fearless firefighter ran into the burning building to help.", "meaning": "Having no fear; very brave."},
    "hopeless": {"sentence": "She felt hopeless about the maths test until her friend helped her.", "meaning": "Feeling as if there is no chance of things getting better."},
    "restless": {"sentence": "The children were restless on the long coach journey home.", "meaning": "Unable to keep still or relax."},
    # Week 21 — suffix -ly
    "quickly": {"sentence": "She quickly packed her bag so she would not be late.", "meaning": "Done with speed; in a fast way."},
    "slowly": {"sentence": "The snail moved slowly across the wet pavement.", "meaning": "Done without much speed; in a slow way."},
    "sadly": {"sentence": "He sadly said goodbye to his teacher at the end of the year.", "meaning": "In an unhappy way; with sadness."},
    "badly": {"sentence": "He hurt his knee badly when he fell off the climbing frame.", "meaning": "In a poor or harmful way; not well."},
    "really": {"sentence": "She was really pleased when she got all ten words right.", "meaning": "Used to emphasise how true or strong something is; very."},
    "finally": {"sentence": "After months of practice, she finally learned to ride her bike.", "meaning": "After a long time or after several attempts; at last."},
    "suddenly": {"sentence": "Suddenly the lights went out and everyone gasped.", "meaning": "Happening quickly and without any warning."},
    "gently": {"sentence": "She gently stroked the sleeping cat on the sofa.", "meaning": "In a soft, careful, and kind way."},
    "simply": {"sentence": "The teacher explained it simply so everyone understood.", "meaning": "In a clear, easy way; without complication."},
    "easily": {"sentence": "He easily remembered all his spellings because he had practised.", "meaning": "Without difficulty; in an effortless way."},
    # Week 22 — contractions
    "can't": {"sentence": "I can't reach the top shelf — it is too high.", "meaning": "Short for 'cannot' — not able to do something."},
    "don't": {"sentence": "Please don't run in the corridor — it is not safe.", "meaning": "Short for 'do not' — used to tell someone not to do something."},
    "didn't": {"sentence": "She didn't hear the bell because she had her earphones in.", "meaning": "Short for 'did not' — something that did not happen."},
    "isn't": {"sentence": "That isn't the right classroom — yours is next door.", "meaning": "Short for 'is not'."},
    "wasn't": {"sentence": "He wasn't in school on Monday because he had a cold.", "meaning": "Short for 'was not'."},
    "haven't": {"sentence": "I haven't finished my homework yet — I need more time.", "meaning": "Short for 'have not'."},
    "I'll": {"sentence": "I'll bring my library book back on Friday, I promise.", "meaning": "Short for 'I will'."},
    "we're": {"sentence": "We're going on a school trip to the farm next week.", "meaning": "Short for 'we are'."},
    "it's": {"sentence": "It's raining outside, so we are having indoor break today.", "meaning": "Short for 'it is'."},
    "they're": {"sentence": "They're coming to the Christmas concert to watch us perform.", "meaning": "Short for 'they are'."},
    # Week 23 — possessive apostrophe
    "dog's": {"sentence": "The dog's lead was hanging by the front door.", "meaning": "Something belonging to the dog."},
    "cat's": {"sentence": "The cat's bowl was filled with fresh food every morning.", "meaning": "Something belonging to the cat."},
    "girl's": {"sentence": "The girl's coat was left on the cloakroom peg.", "meaning": "Something belonging to one girl."},
    "boy's": {"sentence": "The boy's trainers were muddy after playing football.", "meaning": "Something belonging to one boy."},
    "teacher's": {"sentence": "The teacher's desk was covered in books and coloured pens.", "meaning": "Something belonging to the teacher."},
    "sister's": {"sentence": "She borrowed her sister's red hair clip for the day.", "meaning": "Something belonging to a sister."},
    "mother's": {"sentence": "We made a special card for Mother's Day as a surprise.", "meaning": "Something belonging to a mother."},
    "friend's": {"sentence": "She left her coat at her friend's house after the sleepover.", "meaning": "Something belonging to a friend."},
    "bird's": {"sentence": "We watched from the window as the bird's chicks hatched.", "meaning": "Something belonging to the bird."},
    "child's": {"sentence": "A child's imagination is one of the most wonderful things.", "meaning": "Something belonging to one child."},
    # Week 24 — -tion
    "station": {"sentence": "We caught the train from the station early on Saturday morning.", "meaning": "A place where trains or buses stop for passengers."},
    "action": {"sentence": "Quick action by the teacher stopped the accident from happening.", "meaning": "Something that you do; the process of doing something."},
    "nation": {"sentence": "People from every nation came to watch the Olympic Games.", "meaning": "A large group of people who share a country and identity."},
    "motion": {"sentence": "The motion of the waves made some passengers feel sick.", "meaning": "The act of moving; movement."},
    "fiction": {"sentence": "Her favourite fiction series is about a girl who can fly.", "meaning": "Stories and books that are made up, not true."},
    "mention": {"sentence": "Did I mention that we are getting a class hamster?", "meaning": "To say or write something briefly, without going into detail."},
    "section": {"sentence": "You will find atlases in the geography section of the library.", "meaning": "One part of something larger."},
    "invention": {"sentence": "The telephone is one of the greatest inventions in history.", "meaning": "Something new that has been created for the first time."},
    "direction": {"sentence": "Follow the signs to go in the right direction for the park.", "meaning": "The way you need to travel to get somewhere."},
    "celebration": {"sentence": "The street party was a wonderful celebration of the summer.", "meaning": "An event or activity to mark something special and joyful."},
    # Week 25 — homophones set 1
    "there": {"sentence": "Put the books over there on the shelf by the door.", "meaning": "In, at, or to that place."},
    "their": {"sentence": "The children hung their coats on the correct pegs.", "meaning": "Belonging to them."},
    "here": {"sentence": "Come and sit here next to me on the carpet.", "meaning": "In this place; nearby."},
    "hear": {"sentence": "Can you hear the rain beating on the classroom windows?", "meaning": "To sense sound with your ears."},
    "see": {"sentence": "Can you see the rainbow through the window?", "meaning": "To notice or look at something with your eyes."},
    "sea": {"sentence": "We collected shells on the beach beside the sea.", "meaning": "A large area of salty water, smaller than an ocean."},
    "to": {"sentence": "She walked to school with her dad every morning.", "meaning": "In the direction of; used before a verb to show purpose."},
    "too": {"sentence": "He wanted some cake too — not just his sister.", "meaning": "Also; more than needed."},
    "two": {"sentence": "She has two pet rabbits called Biscuit and Pepper.", "meaning": "The number 2."},
    # Week 26 — homophones set 2
    "bear": {"sentence": "A polar bear rolled in the snow at the zoo.", "meaning": "A large, heavy wild animal with thick fur."},
    "bare": {"sentence": "She walked across the warm sand with bare feet.", "meaning": "Not covered; having nothing on top."},
    "break": {"sentence": "We have a short break in the morning to eat our snacks.", "meaning": "A pause in an activity; also to smash something apart."},
    "brake": {"sentence": "She squeezed the brake to slow her bicycle down on the hill.", "meaning": "A device that slows or stops a moving vehicle."},
    "night": {"sentence": "She read under the duvet with a torch late at night.", "meaning": "The time when it is dark outside."},
    "knight": {"sentence": "The brave knight rode across the drawbridge to save the princess.", "meaning": "A soldier in armour who served a king or queen in medieval times."},
    "sun": {"sentence": "The sun came out and the whole playground felt warm.", "meaning": "The star at the centre of our solar system that gives us heat and light."},
    "son": {"sentence": "Their son started at our school in September.", "meaning": "A male child in relation to his parents."},
    "be": {"sentence": "Try to be as kind as you can to everyone today.", "meaning": "To exist; to happen; used in forming verbs."},
    "bee": {"sentence": "A busy bee landed on the lavender in the garden.", "meaning": "A flying insect with yellow and black stripes that makes honey."},
    # Week 27 — homophones set 3
    "blue": {"sentence": "She painted the sky a deep blue in her picture.", "meaning": "The colour of a clear sky."},
    "blew": {"sentence": "She blew out all ten candles in one big breath.", "meaning": "Past tense of blow — pushed air out."},
    "whole": {"sentence": "He ate the whole pizza without leaving any slices!", "meaning": "All of something; the complete amount."},
    "hole": {"sentence": "The rabbit disappeared down a dark hole in the ground.", "meaning": "An opening or gap in something."},
    "where": {"sentence": "Can you tell me where you left your reading book?", "meaning": "In or to what place."},
    "wear": {"sentence": "You must wear your PE kit on a Wednesday.", "meaning": "To have clothing or accessories on your body."},
    "one": {"sentence": "She was the one who found the golden ticket in her bag.", "meaning": "The number 1; a single thing or person."},
    "won": {"sentence": "Our school won the inter-school spelling competition!", "meaning": "Past tense of win — came first in a competition."},
    "quite": {"sentence": "The film was quite exciting — I really enjoyed it.", "meaning": "To a certain degree; fairly but not completely."},
    "quiet": {"sentence": "Please be quiet while I read you the next chapter.", "meaning": "Making little or no noise."},
    # Week 28 — exception words 1
    "door": {"sentence": "Please close the door quietly when you leave the room.", "meaning": "A panel that opens and closes to let you in or out."},
    "floor": {"sentence": "She sat cross-legged on the floor to listen to the story.", "meaning": "The flat surface that you walk on inside a building."},
    "poor": {"sentence": "Poor Alfie fell over in the playground and hurt his knee.", "meaning": "Having very little money, or used to show sympathy."},
    "because": {"sentence": "She was smiling because she had got all her spellings right.", "meaning": "For the reason that."},
    "find": {"sentence": "Can you find the page where we left off yesterday?", "meaning": "To discover or come across something."},
    "kind": {"sentence": "It was very kind of you to share your crayons with me.", "meaning": "Friendly, generous, and caring towards others."},
    "mind": {"sentence": "Do you mind if I sit next to you at lunch?", "meaning": "Your thoughts and feelings, or to care about something."},
    "behind": {"sentence": "She left her lunchbox behind on the shelf by mistake.", "meaning": "At or to the back of something."},
    "child": {"sentence": "Every child in the class got a sticker for their hard work.", "meaning": "A young person who is not yet an adult."},
    "wild": {"sentence": "Wild animals need a safe habitat to survive and thrive.", "meaning": "Living in nature; not tamed by humans."},
    # Week 29 — exception words 2
    "climb": {"sentence": "He loves to climb the big oak tree in the park.", "meaning": "To go up something using your hands and feet."},
    "most": {"sentence": "Most children in the class chose to read at lunch time.", "meaning": "The greatest in amount or number; nearly all."},
    "only": {"sentence": "She was the only one who remembered to bring her book.", "meaning": "Just; no more than; with nothing else."},
    "both": {"sentence": "Both sisters won a prize at the school talent show.", "meaning": "Two things or people together; not just one."},
    "old": {"sentence": "The old library book had yellowed pages and a faded cover.", "meaning": "Having existed for a long time."},
    "cold": {"sentence": "Wrap up warm — it is cold and frosty outside this morning.", "meaning": "Having a low temperature; not warm."},
    "gold": {"sentence": "She won a gold medal in the swimming gala.", "meaning": "A shiny yellow precious metal, often used for medals and jewellery."},
    "hold": {"sentence": "Hold my hand when we cross the busy road.", "meaning": "To keep something in your hands or arms."},
    "told": {"sentence": "He told his teacher about the wasp's nest in the hedge.", "meaning": "Past tense of tell — shared information with someone."},
    "every": {"sentence": "She practises her spellings every evening before bed.", "meaning": "Each one without exception; all of them."},
    # Week 30 — exception words 3
    "everybody": {"sentence": "Everybody cheered when the team scored the winning goal.", "meaning": "Every single person; all people."},
    "even": {"sentence": "Even on a rainy day, they found something fun to do.", "meaning": "Used to emphasise something surprising; flat and equal."},
    "great": {"sentence": "You have done a great job on your project — well done!", "meaning": "Very large, important, or very good."},
    "steak": {"sentence": "Dad cooked a steak on the barbecue for a special dinner.", "meaning": "A thick slice of beef or fish, usually cooked quickly."},
    "pretty": {"sentence": "She drew a pretty pattern of flowers around her bookmark.", "meaning": "Pleasing to look at; also used to mean fairly or quite."},
    "after": {"sentence": "We can play outside after we have eaten our lunch.", "meaning": "Later in time; following something."},
    "fast": {"sentence": "The cheetah is the fastest animal on land in the world.", "meaning": "Moving or doing things quickly."},
    "last": {"sentence": "She was the last person to sit down in the assembly hall.", "meaning": "Coming after everyone or everything else; most recent."},
    "past": {"sentence": "Walk straight past the post office and turn left at the junction.", "meaning": "Gone by; a time that has already happened; beyond a place."},
    # Week 31 — exception words 4
    "father": {"sentence": "Her father reads her a bedtime story every single night.", "meaning": "A male parent."},
    "class": {"sentence": "Our class is learning about the Victorians this half term.", "meaning": "A group of children taught together, or a category."},
    "grass": {"sentence": "The grass was wet with dew early on Tuesday morning.", "meaning": "Green plants with thin leaves that cover lawns and fields."},
    "pass": {"sentence": "Pass the pencils around the table so everyone has one.", "meaning": "To hand something to someone; to go by; to succeed in a test."},
    "plant": {"sentence": "We planted sunflower seeds and watched them grow all summer.", "meaning": "A living thing that grows in soil and uses sunlight to make food."},
    "path": {"sentence": "Follow the path through the woods until you reach the gate.", "meaning": "A track made for people to walk along."},
    "bath": {"sentence": "She had a warm bath with bubbles before going to bed.", "meaning": "A large tub that you fill with water to wash in."},
    "hour": {"sentence": "We spent an hour doing art in the sunshine outside.", "meaning": "A period of sixty minutes."},
    "move": {"sentence": "Please move your chair so there is more room for everyone.", "meaning": "To go from one place to another; to shift position."},
    "improve": {"sentence": "She worked hard every week to improve her handwriting.", "meaning": "To get better at something."},
    # Week 32 — exception words 5
    "prove": {"sentence": "Can you prove that your answer is correct by showing your working?", "meaning": "To show that something is definitely true."},
    "sure": {"sentence": "Are you sure that you put your homework in the tray?", "meaning": "Completely certain; having no doubt."},
    "sugar": {"sentence": "Eating too much sugar is not good for your teeth.", "meaning": "A sweet white substance used in cooking and baking."},
    "eye": {"sentence": "She closed one eye and looked through the telescope.", "meaning": "The part of the body you use to see."},
    "could": {"sentence": "She could hear music playing in the hall next door.", "meaning": "Was able to; used to show possibility."},
    "should": {"sentence": "You should always listen carefully to the instructions.", "meaning": "Used to say something is the right or expected thing to do."},
    "would": {"sentence": "Would you like to read the next chapter of our class novel?", "meaning": "Used to talk about what someone wants or what might happen."},
    "who": {"sentence": "Who left their umbrella on the cloakroom floor?", "meaning": "Which person."},
    "any": {"sentence": "Is there any paint left or have we used it all?", "meaning": "One or some; used in questions or negatives."},
    # Week 33 — exception words 6
    "many": {"sentence": "Many children in our school walk or cycle to get here.", "meaning": "A large number of people or things."},
    "clothes": {"sentence": "Hang your clothes on the peg when you get changed for PE.", "meaning": "Things you wear on your body, such as shirts and trousers."},
    "busy": {"sentence": "The post office was very busy on Christmas Eve.", "meaning": "Having a lot to do; not free."},
    "people": {"sentence": "Lots of people came to watch the school play.", "meaning": "Human beings, especially a large group."},
    "water": {"sentence": "Drink plenty of water throughout the day to stay healthy.", "meaning": "The clear liquid that all living things need to survive."},
    "again": {"sentence": "She read the poem again and again until she knew it by heart.", "meaning": "One more time; returning to an earlier state."},
    "half": {"sentence": "Cut the apple in half so you can share it equally.", "meaning": "One of two equal parts of something."},
    "money": {"sentence": "She saved all her birthday money to buy a new book.", "meaning": "Coins and notes used to buy things."},
    "Christmas": {"sentence": "Our class made paper chains to decorate the room for Christmas.", "meaning": "A holiday on 25th December celebrating the birth of Jesus."},
    "parents": {"sentence": "Her parents came to watch the sports day races.", "meaning": "A person's mother and father."},
    # Week 34 — exception words 7
    "everyone": {"sentence": "Everyone stood up when the head teacher walked into the hall.", "meaning": "Every person; all people in a group."},
    "though": {"sentence": "Even though it was cold, they played outside at lunch.", "meaning": "Despite the fact that; used to introduce a contrast."},
    "although": {"sentence": "Although the test was tricky, she felt she had done her best.", "meaning": "Despite something; even if something is true."},
    "thought": {"sentence": "He thought carefully before writing his answer in full sentences.", "meaning": "Something you think about in your mind; past tense of think."},
    "through": {"sentence": "She walked through the park to get to her grandmother's house.", "meaning": "Moving from one side to the other; by means of."},
    "or": {"sentence": "Would you prefer orange juice or apple juice with your lunch?", "meaning": "Used to offer a choice between two things."},
    "Mr": {"sentence": "Mr Johnson teaches Year 2 at our primary school.", "meaning": "A title used before a man's surname."},
    "Mrs": {"sentence": "Mrs Patel is our headteacher and she is always very kind.", "meaning": "A title used before a married woman's surname."},
    "mother": {"sentence": "Her mother helped her practise her spellings every evening.", "meaning": "A female parent."},
    # Week 35 — multisyllabic challenge
    "necessary": {"sentence": "It is necessary to bring your reading book every day.", "meaning": "Needed; something that must be done or had."},
    "separate": {"sentence": "Please separate your recyclables from your general waste.", "meaning": "To divide; to keep apart; not together."},
    "different": {"sentence": "Every child in the class has a different favourite book.", "meaning": "Not the same; unlike something else."},
    "favourite": {"sentence": "Her favourite subject at school is art and design.", "meaning": "The one you like most of all."},
    "interesting": {"sentence": "She found volcanoes really interesting after the science lesson.", "meaning": "Making you want to know more; not boring."},
    "especially": {"sentence": "She loves science, especially experiments with water and colours.", "meaning": "More than others; particularly."},
    "definitely": {"sentence": "She was definitely the most prepared for the class debate.", "meaning": "Certainly; without any doubt."},
    "remember": {"sentence": "Please remember to bring back your signed permission slip.", "meaning": "To keep something in your mind; to recall something."},
    "February": {"sentence": "Valentine's Day falls on the 14th of February each year.", "meaning": "The second month of the year, with 28 or 29 days."},
    "library": {"sentence": "We visit the school library every Tuesday to change our books.", "meaning": "A place where books are kept and can be borrowed."},
    # Week 36 — Year 3 bridge
    "knowledge": {"sentence": "Reading lots of books will build your knowledge enormously.", "meaning": "Facts, information, and skills learned through experience or education."},
    "straight": {"sentence": "Draw a straight line under the title using a ruler.", "meaning": "Going in one direction without bending or curving."},
    "thorough": {"sentence": "She did a thorough job of tidying the art cupboard.", "meaning": "Doing something very carefully and completely."},
    "guard": {"sentence": "A guard stood at the entrance to the ancient castle.", "meaning": "A person who watches over and protects something."},
    "guide": {"sentence": "A kind guide showed us around the museum all afternoon.", "meaning": "A person who shows others the way; to help someone."},
    "guitar": {"sentence": "She practises the guitar for twenty minutes every evening.", "meaning": "A musical instrument with strings that you pluck or strum."},
    "disappear": {"sentence": "The magician made the coin disappear right before our eyes.", "meaning": "To go out of sight; to stop being visible."},
    "immediately": {"sentence": "Please come immediately — your lunch is getting cold.", "meaning": "Right away; without any delay."},
    "actually": {"sentence": "He was actually quite nervous before going on stage.", "meaning": "Used to say what is really true, especially when surprising."},
    "therefore": {"sentence": "She revised hard and therefore felt confident on test day.", "meaning": "For that reason; as a result."},
}


WEEK_ROWS = [
    {"week": 1, "focus": "Baseline review: Y1 consonant blends", "words": "frost, stamp, splash, string, scrunch, drift, thrust, sprint, crisp, blast"},
    {"week": 2, "focus": "/dʒ/ spelled dge/ge at end of words", "words": "badge, bridge, fudge, hedge, lodge, cage, huge, stage, page, edge"},
    {"week": 3, "focus": "/dʒ/ spelled g before e/i/y", "words": "gem, giant, magic, energy, ginger, gym, danger, engine, gentle, giraffe*"},
    {"week": 4, "focus": "/s/ spelled c before e/i/y", "words": "ice, dance, fence, city, circle, pencil, cycle, cell, race, mice"},
    {"week": 5, "focus": "/n/ spelled kn/gn at start of words", "words": "knee, knock, knife, know, knot, gnaw, gnome, sign, gnat, kneel*"},
    {"week": 6, "focus": "/r/ spelled wr at start of words", "words": "write, wrist, wrap, wrong, wreck, wrinkle, wren, wrestle*, wreath*, wriggle*"},
    {"week": 7, "focus": "Unstressed /l/ spelled –le/–el/–al", "words": "table, apple, little, camel, tunnel, travel, metal, pedal, hospital*, animal"},
    {"week": 8, "focus": "Words ending –y (says /i/)", "words": "happy, funny, family, party, twenty, story, sunny, lucky, hungry, memory*"},
    {"week": 9, "focus": "Plural –es on nouns ending –y", "words": "babies, ladies, cities, families, ponies, stories, parties, countries, hobbies, bunnies"},
    {"week": 10, "focus": "Suffixes on –y words (y→i)", "words": "tried, tries, trying, happier, happiest, carried, carrying, dried, hurried, replying*"},
    {"week": 11, "focus": "Suffixes on words ending –e (drop e)", "words": "hoping, hoped, shining, riding, rider, baking, baker, smiling, smiled, deciding*"},
    {"week": 12, "focus": "Doubling final consonant (CVC + suffix)", "words": "hopping, hopped, running, runner, biggest, sadder, patted, humming, swimmer, forgetting*"},
    {"week": 13, "focus": "/ɒ/ spelled a after w/qu", "words": "wander, swan, quantity, squash, wasp, quality, quarrel, wallet, swap, squabble*"},
    {"week": 14, "focus": "/ɜː/ spelled or after w", "words": "word, work, world, worm, worth, worship, worse, worst, network*, wordless*"},
    {"week": 15, "focus": "/ɔː/ spelled ar after w", "words": "warm, ward, warn, wart, dwarf, award, reward, swarm, towards, warden*"},
    {"week": 16, "focus": "/ʒ/ spelled s", "words": "treasure, measure, pleasure, usual, television, casual, visual, leisure*, azure*, unusual"},
    {"week": 17, "focus": "Suffix –ment", "words": "enjoyment, argument, government, movement, statement, equipment, payment, treatment, excitement, arrangement*"},
    {"week": 18, "focus": "Suffix –ness", "words": "happiness, kindness, sadness, darkness, illness, weakness, thickness, business, awareness*, fairness"},
    {"week": 19, "focus": "Suffix –ful", "words": "careful, helpful, useful, playful, wonderful, colourful, thankful, painful, powerful, beautiful*"},
    {"week": 20, "focus": "Suffix –less", "words": "careless, helpless, useless, harmless, endless, homeless, painless, fearless, hopeless, restless*"},
    {"week": 21, "focus": "Suffix –ly", "words": "quickly, slowly, sadly, badly, really, finally, suddenly, gently, simply, easily"},
    {"week": 22, "focus": "Contractions", "words": "can't, don't, didn't, isn't, wasn't, haven't, I'll, we're, it's, they're"},
    {"week": 23, "focus": "Possessive apostrophe (singular)", "words": "dog's, cat's, girl's, boy's, teacher's, sister's, mother's, friend's, bird's, child's"},
    {"week": 24, "focus": "Words ending –tion", "words": "station, action, nation, motion, fiction, mention, section, invention*, direction, celebration*"},
    {"week": 25, "focus": "Homophones 1", "words": "there, their, they're, here, hear, see, sea, to, too, two"},
    {"week": 26, "focus": "Homophones 2", "words": "bear, bare, break, brake, night, knight, sun, son, be, bee"},
    {"week": 27, "focus": "Homophones 3", "words": "blue, blew, whole, hole, where, wear, one, won, quite, quiet"},
    {"week": 28, "focus": "Common exception words 1", "words": "door, floor, poor, because, find, kind, mind, behind, child, wild"},
    {"week": 29, "focus": "Common exception words 2", "words": "climb, most, only, both, old, cold, gold, hold, told, every"},
    {"week": 30, "focus": "Common exception words 3", "words": "everybody, even, great, steak, pretty, beautiful, after, fast, last, past"},
    {"week": 31, "focus": "Common exception words 4", "words": "father, class, grass, pass, plant, path, bath, hour, move, improve"},
    {"week": 32, "focus": "Common exception words 5", "words": "prove, sure, sugar, eye, could, should, would, who, whole, any"},
    {"week": 33, "focus": "Common exception words 6", "words": "many, clothes, busy, people, water, again, half, money, Christmas, parents"},
    {"week": 34, "focus": "Common exception words 7", "words": "everyone, though, although, thought, through, world, or, Mr, Mrs, mother"},
    {"week": 35, "focus": "Challenge extension (multisyllabic, less regular)", "words": "necessary, separate, different, favourite, interesting, especially, definitely, remember, February, library"},
    {"week": 36, "focus": "Final consolidation / Year 3 bridge", "words": "knowledge, straight, thorough, guard, guide, guitar, disappear, immediately, actually, therefore"},
]
